# This playbook will install and configure WordPress on the webservers group of hosts.
---
- hosts: webservers
  become: yes
  gather_facts: no
  

  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    db_host: "{{ lookup('env', 'DB_HOST') }}"

  tasks:
    - name: Install python3-libdnf5
      dnf:
        name:
          - python3-libdnf5
        use_backend: dnf4
    - name: Debug - Print ansible facts
      debug:
        msg: 
          - "Distribution: {{ ansible_distribution }}"
          - "Distribution version: {{ ansible_distribution_version }}"
          - "Package manager: {{ ansible_pkg_mgr }}"
    
    #- name: Enable Amazon Linux Extras repository
    #  command: amazon-linux-extras enable php7.4
    #  become: yes

    - name: Install required packages
      ansible.builtin.dnf5:
        name:
          - python3-libdnf5
          - httpd
          - php
          - php-mysqlnd
        state: present
        #use_backend: dnf5
      become: yes

    - name: Start and enable Apache
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes

    - name: Configure WordPress
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php

    - name: Set permissions
      file:
        path: /var/www/html/wordpress
        owner: apache
        group: apache
        mode: '0755'
        recurse: yes