# This playbook will install and configure WordPress on the webservers group of hosts.
---
- hosts: webservers
  become: yes
  vars:
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    db_host: "{{ lookup('env', 'DB_HOST') }}"

  tasks:
    - name: Install required packages
      dnf:
        name:
          - httpd
          - php
          - php-mysqlnd
        state: present

    - name: Start and enable Apache
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        remote_src: yes

    - name: Configure WordPress
      template:
        src: ../templates/wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php

    - name: Set permissions
      file:
        path: /var/www/html/wordpress
        owner: apache
        group: apache
        mode: '0755'
        recurse: yes